# Generated by Django 3.2.2 on 2021-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0012_auto_20210515_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactu',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
